airstats:
  outputs:
    dev:
      account: LJEMQYF-AF72212
      database: airstats
      password: Easymoney_1234
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: ESLAMASFOUR
      warehouse: COMPUTE_WH
  target: dev
